site_name: Hubery's Dreamland
site_url: https://hubery258.github.io/dreamland-hubery/
nav:
  - CS:
    - c程: docs/cs/c_language.md
    - CS50X: docs/cs/cs50x/index.md
  - About Me:
    - 随笔: docs/life/pieces/index.md
    - Reading: docs/life/reading/index.md
theme:
  name: material