site_name: Hubery's Dreamland
site_url: https://hubery258.github.io/dreamland-hubery/
nav:
  - CS:
    - c程: cs/c_language.md
    - CS50X: cs/cs50x/index.md
  - About Me:
    - 随笔: life/pieces/index.md
    - Reading: life/reading/index.md
theme:
  name: material