site_name: Hubery's Dreamland
site_url: https://hubery258.github.io/dreamland-hubery/

theme:
  name: material
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: 关闭自动模式
    
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: deep orange 
      accent: blue 
      toggle:
        icon: material/brightness-7
        name: 切换至夜间模式 

    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式
    
  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/git-alt #右上角图标
    logo: logo
    admonition:
      note: fontawesome/solid/note-sticky
      tip: fontawesome/solid/bullhorn
      warning: fontawesome/solid/triangle-exclamation
      example: fontawesome/solid/flask
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info


extra:
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/2134294131
      name: bilibili
    - icon: fontawesome/brands/github
      link: https://github.com/hubery258
      name: github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

repo_url: https://github.com/hubery258/dreamland-hubery
repo_name: dreamland-hubery

nav:
  - CS:
    - CS50X: cs/CS50X.md
    - Computer Science Crash Course: cs/cs速成.md
    - mkdocs配置: cs/mkdocs.md
    - Missing Semester:
      - git: cs/Missing Semester/git.md
      - lec1 SHELL: cs/Missing Semester/lec1.md
      - lec2 SHELL脚本: cs/Missing Semester/lec2.md 
      - lec3 Vim: cs/Missing Semester/lec3.md
      - lec4 数据处理: cs/Missing Semester/lec4.md
      - lec6 git: cs/Missing Semester/lec6.md
  - ZJU:
    - 大一课程经验: school/zju.md
  - project:
    - Simple Tasker: project/simpletasker.md
  - blog:
    - 千问集: life/question.md
    - daily blog: 
      - 25·11: life/pieces/25_11.md
      - 25·12: life/pieces/25_12.md
      - 26·1: life/pieces/26_1.md
    - Reading: 
      - 一次讲座: life/reading/好趣味与坏艺术讲座.md
      - 当尼采哭泣: life/reading/nicai.md
      - 堕落 流放与王国: life/reading/camus1.md
      - 在绝望之巅: life/reading/despair.md
      - 我不在意人类的失败: life/reading/failure.md
      - 将熟悉变为陌生: life/reading/strange.md
      - 罪与罚: life/reading/crime.md
      - 福格行为模型: life/reading/action.md
    - Music:
      - 26年1月: life/music/26_1.md
    - 思想笔记:
      - 自律: lfie/note/focus.md
